modLoader = "javafml"
loaderVersion = "[40,)"
license = "All Rights Reserved"
[[mods]]
modId = "discdissection"
version = "${file.jarVersion}"
displayName = "Orcinus"
authors = "Orcinus"
description = '''
This mod adds the disc fragments for other minecraft discs.
'''
[[dependencies.discdissection]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.discdissection]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"
